spring:
  application:
    name: oerp
  datasource:
    url: jdbc:mysql://localhost:3307/oerp?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: caffeine
    cache-names:
      # 图片验证码缓存
      - IMAGE_CAPTCHA_CACHE
      # 短信验证码缓存
      - SMS_CAPTCHA_CACHE
    couchbase:
      expiration: 300

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mybatis/xml/**/*.xml
  global-config:
    banner: false
server:
  port: 8080
  servlet:
    context-path: /api/v1